class NotificationModel {
  final String id;
  final String title;
  final String message;
  final String userId;
  final String type; // 'transfer', 'event', 'reminder', etc.
  final Map<String, dynamic>? data; // Extra data for notification actions
  final bool isRead;
  final DateTime createdAt;
  final DateTime? readAt;
  final List<NotificationAction> actions;

  NotificationModel({
    required this.id,
    required this.title,
    required this.message,
    required this.userId,
    required this.type,
    this.data,
    this.isRead = false,
    required this.createdAt,
    this.readAt,
    this.actions = const [],
  });

  Map<String, dynamic> toRtdbMap() {
    return {
      'title': title,
      'message': message,
      'userId': userId,
      'type': type,
      'data': data,
      'isRead': isRead,
      'createdAt': createdAt.millisecondsSinceEpoch,
      'readAt': readAt?.millisecondsSinceEpoch,
      'actions': actions.map((a) => a.toMap()).toList(),
    };
  }

  factory NotificationModel.fromRtdb(String id, Map<dynamic, dynamic> map) {
    return NotificationModel(
      id: id,
      title: map['title'] as String? ?? '',
      message: map['message'] as String? ?? '',
      userId: map['userId'] as String? ?? '',
      type: map['type'] as String? ?? 'general',
      data: map['data'] != null ? Map<String, dynamic>.from(map['data']) : null,
      isRead: map['isRead'] as bool? ?? false,
      createdAt: DateTime.fromMillisecondsSinceEpoch(
        map['createdAt'] as int? ?? 0,
      ),
      readAt: map['readAt'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['readAt'] as int)
          : null,
      actions: (map['actions'] as List<dynamic>? ?? [])
          .map((a) => NotificationAction.fromMap(Map<String, dynamic>.from(a)))
          .toList(),
    );
  }

  NotificationModel copyWith({
    String? id,
    String? title,
    String? message,
    String? userId,
    String? type,
    Map<String, dynamic>? data,
    bool? isRead,
    DateTime? createdAt,
    DateTime? readAt,
    List<NotificationAction>? actions,
  }) {
    return NotificationModel(
      id: id ?? this.id,
      title: title ?? this.title,
      message: message ?? this.message,
      userId: userId ?? this.userId,
      type: type ?? this.type,
      data: data ?? this.data,
      isRead: isRead ?? this.isRead,
      createdAt: createdAt ?? this.createdAt,
      readAt: readAt ?? this.readAt,
      actions: actions ?? this.actions,
    );
  }
}

class NotificationAction {
  final String label;
  final String type; // 'navigate', 'action', 'dismiss'
  final String? target; // Route name or action identifier
  final Map<String, dynamic>? params;

  NotificationAction({
    required this.label,
    required this.type,
    this.target,
    this.params,
  });

  Map<String, dynamic> toMap() {
    return {'label': label, 'type': type, 'target': target, 'params': params};
  }

  factory NotificationAction.fromMap(Map<String, dynamic> map) {
    return NotificationAction(
      label: map['label'] as String? ?? '',
      type: map['type'] as String? ?? 'dismiss',
      target: map['target'] as String?,
      params: map['params'] != null
          ? Map<String, dynamic>.from(map['params'])
          : null,
    );
  }
}

// Factory methods untuk membuat notifikasi spesifik
extension NotificationFactory on NotificationModel {
  static NotificationModel createTransferNotification({
    required String userId,
    required double amount,
    required String senderName,
    required String transactionId,
    required String walletName,
  }) {
    return NotificationModel(
      id: '', // Will be generated by Firebase
      title: 'Transfer Diterima',
      message:
          'Anda menerima transfer sebesar Rp ${_formatAmount(amount)} dari $senderName ke wallet $walletName.',
      userId: userId,
      type: 'transfer',
      data: {
        'transactionId': transactionId,
        'amount': amount,
        'senderName': senderName,
        'walletName': walletName,
      },
      createdAt: DateTime.now(),
      actions: [
        NotificationAction(
          label: 'Lihat Detail',
          type: 'navigate',
          target: '/transaction-detail',
          params: {'transactionId': transactionId},
        ),
      ],
    );
  }

  static NotificationModel createEventNotification({
    required String userId,
    required String eventName,
    required String message,
    String? eventId,
  }) {
    return NotificationModel(
      id: '',
      title: 'Acara: $eventName',
      message: message,
      userId: userId,
      type: 'event',
      data: {'eventId': eventId, 'eventName': eventName},
      createdAt: DateTime.now(),
      actions: eventId != null
          ? [
              NotificationAction(
                label: 'Lihat Acara',
                type: 'navigate',
                target: '/events',
                params: {'eventId': eventId},
              ),
            ]
          : [],
    );
  }

  static String _formatAmount(double amount) {
    // Simple formatting - you can use your existing IdrFormatters
    return amount
        .toStringAsFixed(0)
        .replaceAllMapped(
          RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
          (Match m) => '${m[1]}.',
        );
  }
}
