// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEY4qi9nQgZnuprH0rGhy8A_I3Cujbrig',
    appId: '1:427662349355:web:f9e0c7de24f2881d22066e',
    messagingSenderId: '427662349355',
    projectId: 'moneytracker-d2a02',
    authDomain: 'moneytracker-d2a02.firebaseapp.com',
    storageBucket: 'moneytracker-d2a02.firebasestorage.app',
    measurementId: 'G-9H66K16P4E',
    databaseURL: 'https://moneytracker-d2a02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvuReIyZZbPz3eXC_Qgd9YCWh6uajwzM',
    appId: '1:427662349355:android:c385d87a1fa5c1c722066e',
    messagingSenderId: '427662349355',
    projectId: 'moneytracker-d2a02',
    storageBucket: 'moneytracker-d2a02.firebasestorage.app',
    databaseURL: 'https://moneytracker-d2a02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoK0XyiDBQS0lqcwI7cFGFg9IHG1xMPDI',
    appId: '1:427662349355:ios:7a3dbd20bfac5b1a22066e',
    messagingSenderId: '427662349355',
    projectId: 'moneytracker-d2a02',
    storageBucket: 'moneytracker-d2a02.firebasestorage.app',
    iosBundleId: 'com.moneytracker.moneyTracker',
    databaseURL: 'https://moneytracker-d2a02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoK0XyiDBQS0lqcwI7cFGFg9IHG1xMPDI',
    appId: '1:427662349355:ios:7a3dbd20bfac5b1a22066e',
    messagingSenderId: '427662349355',
    projectId: 'moneytracker-d2a02',
    storageBucket: 'moneytracker-d2a02.firebasestorage.app',
    iosBundleId: 'com.moneytracker.moneyTracker',
    databaseURL: 'https://moneytracker-d2a02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEY4qi9nQgZnuprH0rGhy8A_I3Cujbrig',
    appId: '1:427662349355:web:0cbc0cc9a2fe755522066e',
    messagingSenderId: '427662349355',
    projectId: 'moneytracker-d2a02',
    authDomain: 'moneytracker-d2a02.firebaseapp.com',
    storageBucket: 'moneytracker-d2a02.firebasestorage.app',
    measurementId: 'G-RP8CMP2PXX',
    databaseURL: 'https://moneytracker-d2a02-default-rtdb.firebaseio.com',
  );
}
